### PR TITLE
Raytracing

### PR DESCRIPTION
**Pull request by MichielStock**

### CODE REVIEW

**Review by csangara — COMMENTED** [review]
The draw_circle function is based on the midpoint circle algorithm, and I think that was designed for integers. I'm trying to draw a circle on a grid, so I'm not sure how floating points would work with that.

**Review by csangara — COMMENTED** [review]
When I tried changing get_neighbors to return an iterator and measure the performance with @time, the iterator is faster but I think it also uses more memory. 
image

**Comment by MichielStock** [comment]
I guess speed is more important than your memory footprint?

**Comment by csangara** [comment]
I think so as well, so I will use the iterator.

Side note: I can't come up with a good heuristic function for A* (especially with multiple objects in the scene), so I will leave the main function as Dijkstra.

**Pull request merged**
